### ISSUE TITLE
issues when training

### ISSUE THREAD

**Issue by okami666** [zsdonghao/SRGAN#25]
Thank you for publishing this work.
Currently when I am run the main.py when training,I met with such issues:

Traceback (most recent call last):
  File "/home/weasly/\SRGAN/SRGAN-master/SRGAN-master/main.py", line 316, in <module>
    train()
  File "/home/weasly/SRGAN/SRGAN-master/SRGAN-master/main.py", line 141, in train
    print('sample HR sub-image:',sample_imgs_384.shape, sample_imgs_384.min(), sample_imgs_384.max())
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

the issue seem to be related to:
[!] Load checkpoint/g_srgan.npz failed!
[!] Load checkpoint/g_srgan_init.npz failed!
[!] Load checkpoint/d_srgan.npz failed!

how can I solve the problem?thanks a lot

**Comment by jiaozixian** [comment]
check your train data path ，the code has not read the data。

**Comment by okami666** [comment]
thank you

**Comment by zhuguoguo123** [comment]
Did you solve the problem? Is this file needed to be prepared in advance?

thank you

**Comment by zhuguoguo123** [comment]
Hello ! Are these  files needed to be prepared in advance? Did you have these  files??  Thank you for your help . @jiaozixian

**Comment by relh** [comment]
if you have `.jpg` images you will get this error because main.py looks for `*.png`

**Comment by NYing** [comment]
I have the same problem.I read the data successfully,but get wrong after "sample_imgs_96 = tl.prepro.threading_data(sample_imgs_384, fn=downsample_fn)",the list sample_imgs_96 is none.I met with such issues:
File "main.py", line 140, in train
    print('sample LR sub-image:', sample_imgs_96.shape, sample_imgs_96.min(), sample_imgs_96.max())
  File "/home/NieYing/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
TypeError: '<=' not supported between instances of 'NoneType' and 'NoneType'
how can I solve the problem?thanks a lot.@zsdonghao
