### ISSUE TITLE
following error occured training own image 

### ISSUE THREAD

**Issue by sukkyusun** [zsdonghao/SRGAN#27]
Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
('sample HR sub-image:', (16,), None, None)
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user01/anaconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/user01/SRGAN-master/utils.py", line 24, in downsample_fn
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
  File "/home/user01/SRGAN-master/tensorlayer/prepro.py", line 834, in imresize
    if x.shape[-1] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Traceback (most recent call last):
  File "/home/user01/SRGAN-master/main.py", line 316, in <module>
    train()
  File "/home/user01/SRGAN-master/main.py", line 144, in train
    tl.vis.save_images(sample_imgs_96, [ni, ni], save_dir_ginit+'/_train_sample_96.png')
  File "/home/user01/SRGAN-master/tensorlayer/visualize.py", line 54, in save_images
    return imsave(images, size, image_path)
  File "/home/user01/SRGAN-master/tensorlayer/visualize.py", line 51, in imsave
    return scipy.misc.imsave(path, merge(images, size))
  File "/home/user01/SRGAN-master/tensorlayer/visualize.py", line 42, in merge
    h, w = images.shape[1], images.shape[2]
IndexError: tuple index out of range
('sample LR sub-image:', (16,), None, None)

Process finished with exit code 1

**Comment by sukkyusun** [comment]
i think input io error

**Comment by sukkyusun** [comment]
solved, converting image to jpg
