### ISSUE TITLE
Error happened when training

### ISSUE THREAD

**Issue by lemony1314** [zsdonghao/SRGAN#38]
**Epoch [ 0/100]   49 time: 0.9090s, mse: 0.07975296 
Traceback (most recent call last):
  File "/home/hy/PycharmProjects/SRGAN-zsdonghao/main.py", line 316, in <module>
    train()
  File "/home/hy/PycharmProjects/SRGAN-zsdonghao/main.py", line 175, in train
    errM, _ = sess.run([mse_loss, g_optim_init], {t_image: b_imgs_96, t_target_image: b_imgs_384})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 975, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (2, 96, 96, 3) for Tensor u't_image_input_to_SRGAN_generator:0', which has shape '(16, 96, 96, 3)'

Process finished with exit code 1**

When training , a error happened (Value error).
Could you please tell me why it happened?
thanks a lot.

**Comment by zsdonghao** [comment]
check this out https://github.com/zsdonghao/SRGAN/issues/32
