### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by shede1988** [zsdonghao/SRGAN#43]
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    train()
  File "main.py", line 141, in train
    print('sample HR sub-image:',sample_imgs_384.shape, sample_imgs_384.min(), sample_imgs_384.max())
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by InderpreetSinghChhabra01** [comment]
Hii,

I am also getting the same error can you please let me know how you have solved it.
