### ISSUE TITLE
Need help, I'm a newer

### ISSUE THREAD

**Issue by AMeancat** [zsdonghao/SRGAN#45]
errorTraceback (most recent call last):
  File "main.py", line 316, in <module>
    train()
  File "main.py", line 73, in train
    net_g = SRGAN_g(t_image, is_train=True, reuse=False)
  File "/home/zhangheng_li/SRGAN/model.py", line 42, in SRGAN_g
    n = SubpixelConv2d(n, scale=2, n_out_channel=None, act=tf.nn.relu, name='pixelshufflerx2/1')
  File "/home/zhangheng_li/SRGAN/tensorlayer/layers.py", line 2193, in SubpixelConv2d
    net_new.outputs = act(_PS(inputs, r=scale, n_out_channel=n_out_channel))
  File "/home/zhangheng_li/SRGAN/tensorlayer/layers.py", line 2175, in _PS
    Xs=tf.split(X,r,3) #b*h*w*r*r
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1234, in split
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3241, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 508, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

**Comment by zsdonghao** [comment]
what is the TF and TL version are you using?

**Comment by AMeancat** [comment]
Really appreciate your reply firstly. I guess its 0.8.0,  our server just reloaded two weeks ago, and I just gave up that. I'll redo that in a few weeks, if any question, I'll request for help again.
REALLY THANKS :)
