### ISSUE TITLE
Question about using my own dataset.

### ISSUE THREAD

**Issue by MikeXlYang** [zsdonghao/SRGAN#46]
I only changed the (using the trained vgg19) 
`config.config.TRAIN.hr_img_path``config.config.TRAIN.lr_img_path`
and validation path
and when I run main.py, it turned out like this
`  Loading fc8: (4096, 1000), (1000,)
Exception in thread threading_and_return:
Traceback (most recent call last):
  File "G:\anacondasetup\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "G:\anacondasetup\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "E:\datasets\srgan\SRGAN-master\tensorlayer\prepro.py", line 87, in apply_fn
    results[i] = fn(data, **kwargs)
  File "E:\datasets\srgan\SRGAN-master\utils.py", line 17, in crop_sub_imgs_fn
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
  File "E:\datasets\srgan\SRGAN-master\tensorlayer\prepro.py", line 232, in crop
    h, w = x.shape[row_index], x.shape[col_index]
AttributeError: 'NoneType' object has no attribute 'shape'`
It seems I failed to load the images.
My image size is 256*320(h*l)
Is there anything else I should have done?
Thx =D

**Comment by MikeXlYang** [comment]
And I changed my dataset to 1920 1024 the same happened

**Comment by MikeXlYang** [comment]
I found it was some error due to windows and the ide I was using and fixed it. THX anyway
BTW, if I want to use the model I trained and imply it to a new image, what should I do, and to which path is the trained model saved?
